# Generated by Django 4.2.17 on 2025-01-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='historical_figure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.historicalfigure'),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='prompt',
            field=models.TextField(help_text='系统消息，用于引导AI角色'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', '用户'), ('assistant', 'AI')], max_length=10),
        ),
    ]
